/**
 * Catálogo nacional de distritos por departamento — usado para marcar (nunca
 * rechazar) obras cuyo `distrito` no pertenece al universo real del
 * `departamento` declarado. Hallazgo DQ-14 (2026-09-08, ver
 * docs/TICKETS_Calidad_Datos_Auditoria_La_Libertad_v1.md): 7 obras de Pataz
 * traían un distrito de otro departamento (Cusco) o inexistente, sin que
 * nada en el ingest lo detectara.
 *
 * Fuente: tabla `territories` de `ceplan-geo` (capa geoespacial derivada de
 * INEI/GEOSERVER, 1,874 distritos — coincide con el total oficial del Perú),
 * exportada una sola vez el 2026-09-08 a este archivo estático porque
 * `infobras` no tiene acceso directo a la base de datos de `ceplan-geo`
 * (apps independientes, sin base compartida). No se vuelve a sincronizar
 * automáticamente — si INEI crea/fusiona distritos, este catálogo queda
 * desactualizado hasta que alguien lo regenere a mano desde la misma fuente.
 */
export const DISTRITOS_POR_DEPARTAMENTO: Readonly<Record<string, ReadonlySet<string>>> = {
  "AMAZONAS": new Set([
    "ARAMANGO",
    "ASUNCION",
    "BAGUA",
    "BAGUA GRANDE",
    "BALSAS",
    "CAJARURO",
    "CAMPORREDONDO",
    "CHACHAPOYAS",
    "CHETO",
    "CHILIQUIN",
    "CHIRIMOTO",
    "CHISQUILLA",
    "CHUQUIBAMBA",
    "CHURUJA",
    "COCABAMBA",
    "COCHAMAL",
    "COLCAMAR",
    "CONILA",
    "COPALLIN",
    "COROSHA",
    "CUISPES",
    "CUMBA",
    "EL CENEPA",
    "EL MILAGRO",
    "EL PARCO",
    "FLORIDA",
    "GRANADA",
    "HUAMBO",
    "HUANCAS",
    "IMAZA",
    "INGUILPATA",
    "JAMALCA",
    "JAZAN",
    "JUMBILLA",
    "LA JALCA",
    "LA PECA",
    "LAMUD",
    "LEIMEBAMBA",
    "LEVANTO",
    "LIMABAMBA",
    "LONGAR",
    "LONGUITA",
    "LONYA CHICO",
    "LONYA GRANDE",
    "LUYA",
    "LUYA VIEJO",
    "MAGDALENA",
    "MARIA",
    "MARISCAL BENAVIDES",
    "MARISCAL CASTILLA",
    "MILPUC",
    "MOLINOPAMPA",
    "MONTEVIDEO",
    "NIEVA",
    "OCALLI",
    "OCUMAL",
    "OLLEROS",
    "OMIA",
    "PISUQUIA",
    "PROVIDENCIA",
    "QUINJALCA",
    "RECTA",
    "RIO SANTIAGO",
    "SAN CARLOS",
    "SAN CRISTOBAL",
    "SAN FRANCISCO DE DAGUAS",
    "SAN FRANCISCO DEL YESO",
    "SAN ISIDRO DE MAINO",
    "SAN JERONIMO",
    "SAN JUAN DE LOPECANCHA",
    "SAN NICOLAS",
    "SANTA CATALINA",
    "SANTA ROSA",
    "SANTO TOMAS",
    "SHIPASBAMBA",
    "SOLOCO",
    "SONCHE",
    "TINGO",
    "TOTORA",
    "TRITA",
    "VALERA",
    "VISTA ALEGRE",
    "YAMBRASBAMBA",
    "YAMON",
  ]),
  "ANCASH": new Set([
    "ABELARDO PARDO LEZAMETA",
    "ACAS",
    "ACO",
    "ACOBAMBA",
    "ACOCHACA",
    "ACOPAMPA",
    "ACZO",
    "AIJA",
    "ALFONSO UGARTE",
    "AMASHCA",
    "ANRA",
    "ANTA",
    "ANTONIO RAYMONDI",
    "AQUIA",
    "ATAQUERO",
    "BAMBAS",
    "BOLOGNESI",
    "BUENA VISTA ALTA",
    "CABANA",
    "CACERES DEL PERU",
    "CAJACAY",
    "CAJAMARQUILLA",
    "CAJAY",
    "CANIS",
    "CARAZ",
    "CARHUAPAMPA",
    "CARHUAZ",
    "CASCA",
    "CASCAPARA",
    "CASHAPAMPA",
    "CASMA",
    "CATAC",
    "CHACAS",
    "CHACCHO",
    "CHAVIN DE HUANTAR",
    "CHIMBOTE",
    "CHINGALPO",
    "CHINGAS",
    "CHIQUIAN",
    "COCHABAMBA",
    "COCHAPETI",
    "COCHAS",
    "COISHCO",
    "COLCABAMBA",
    "COLQUIOC",
    "COMANDANTE NOEL",
    "CONCHUCOS",
    "CONGAS",
    "CORIS",
    "CORONGO",
    "COTAPARACO",
    "CULEBRAS",
    "CUSCA",
    "ELEAZAR GUZMAN BARRON",
    "FIDEL OLIVAS ESCUDERO",
    "HUACACHI",
    "HUACASCHUQUE",
    "HUACCHIS",
    "HUACHIS",
    "HUACLLAN",
    "HUALLANCA",
    "HUANCHAY",
    "HUANDOVAL",
    "HUANTAR",
    "HUARAZ",
    "HUARI",
    "HUARMEY",
    "HUASTA",
    "HUATA",
    "HUAYAN",
    "HUAYLAS",
    "HUAYLLABAMBA",
    "HUAYLLACAYAN",
    "HUAYLLAN",
    "HUAYLLAPAMPA",
    "INDEPENDENCIA",
    "JANGAS",
    "LA LIBERTAD",
    "LA MERCED",
    "LA PAMPA",
    "LA PRIMAVERA",
    "LACABAMBA",
    "LLACLLIN",
    "LLAMA",
    "LLAMELLIN",
    "LLAPO",
    "LLIPA",
    "LLUMPA",
    "LUCMA",
    "MACATE",
    "MALVAS",
    "MANCOS",
    "MANGAS",
    "MARCA",
    "MARCARA",
    "MASIN",
    "MATACOTO",
    "MATO",
    "MIRGAS",
    "MORO",
    "MUSGA",
    "NEPENA",
    "NUEVO CHIMBOTE",
    "OCROS",
    "OLLEROS",
    "PACLLON",
    "PALLASCA",
    "PAMPAROMAS",
    "PAMPAS",
    "PAMPAS CHICO",
    "PAMPAS GRANDE",
    "PARARIN",
    "PARIACOTO",
    "PARIAHUANCA",
    "PAROBAMBA",
    "PAUCAS",
    "PIRA",
    "PISCOBAMBA",
    "POMABAMBA",
    "PONTO",
    "PUEBLO LIBRE",
    "QUICHES",
    "QUILLO",
    "QUINUABAMBA",
    "RAGASH",
    "RAHUAPAMPA",
    "RANRAHIRCA",
    "RAPAYAN",
    "RECUAY",
    "SAMANCO",
    "SAN CRISTOBAL DE RAJAN",
    "SAN JUAN",
    "SAN JUAN DE RONTOY",
    "SAN LUIS",
    "SAN MARCOS",
    "SAN MIGUEL DE ACO",
    "SAN MIGUEL DE CORPANQUI",
    "SAN NICOLAS",
    "SAN PEDRO",
    "SAN PEDRO DE CHANA",
    "SANTA",
    "SANTA CRUZ",
    "SANTA ROSA",
    "SANTIAGO DE CHILCAS",
    "SANTO TORIBIO",
    "SHILLA",
    "SHUPLUY",
    "SICSIBAMBA",
    "SIHUAS",
    "SUCCHA",
    "TAPACOCHA",
    "TARICA",
    "TAUCA",
    "TICAPAMPA",
    "TICLLOS",
    "TINCO",
    "UCO",
    "YANAC",
    "YANAMA",
    "YAUTAN",
    "YAUYA",
    "YUNGAR",
    "YUNGAY",
    "YUPAN",
    "YURACMARCA",
  ]),
  "APURIMAC": new Set([
    "ABANCAY",
    "ANCO_HUALLO",
    "ANDAHUAYLAS",
    "ANDARAPA",
    "ANTABAMBA",
    "CAPAYA",
    "CARAYBAMBA",
    "CHACOCHE",
    "CHALHUANCA",
    "CHALLHUAHUACHO",
    "CHAPIMARCA",
    "CHIARA",
    "CHINCHEROS",
    "CHUQUIBAMBILLA",
    "CIRCA",
    "COCHARCAS",
    "COLCABAMBA",
    "COTABAMBAS",
    "COTARUSE",
    "COYLLURQUI",
    "CURAHUASI",
    "CURASCO",
    "CURPAHUASI",
    "EL ORO",
    "EL PORVENIR",
    "GAMARRA",
    "HAQUIRA",
    "HUACCANA",
    "HUANCARAMA",
    "HUANCARAY",
    "HUANIPACA",
    "HUAQUIRCA",
    "HUAYANA",
    "HUAYLLATI",
    "IHUAYLLO",
    "JOSE MARIA ARGUEDAS",
    "JUAN ESPINOZA MEDRANO",
    "JUSTO APU SAHUARAURA",
    "KAQUIABAMBA",
    "KISHUARA",
    "LAMBRAMA",
    "LOS CHANKAS",
    "LUCRE",
    "MAMARA",
    "MARA",
    "MICAELA BASTIDAS",
    "OCOBAMBA",
    "ONGOY",
    "OROPESA",
    "PACHACONAS",
    "PACOBAMBA",
    "PACUCHA",
    "PAMPACHIRI",
    "PATAYPAMPA",
    "PICHIRHUA",
    "POCOHUANCA",
    "POMACOCHA",
    "PROGRESO",
    "RANRACANCHA",
    "ROCCHACC",
    "SABAINO",
    "SAN ANTONIO",
    "SAN ANTONIO DE CACHI",
    "SAN JERONIMO",
    "SAN JUAN DE CHACNA",
    "SAN MIGUEL DE CHACCRAMPA",
    "SAN PEDRO DE CACHORA",
    "SANAYCA",
    "SANTA MARIA DE CHICMO",
    "SANTA ROSA",
    "SORAYA",
    "TALAVERA",
    "TAMBOBAMBA",
    "TAMBURCO",
    "TAPAIRIHUA",
    "TINTAY",
    "TORAYA",
    "TUMAY HUARACA",
    "TURPAY",
    "TURPO",
    "URANMARCA",
    "VILCABAMBA",
    "VIRUNDO",
    "YANACA",
  ]),
  "AREQUIPA": new Set([
    "ACARI",
    "ACHOMA",
    "ALCA",
    "ALTO SELVA ALEGRE",
    "ANDAGUA",
    "ANDARAY",
    "APLAO",
    "AREQUIPA",
    "ATICO",
    "ATIQUIPA",
    "AYO",
    "BELLA UNION",
    "CABANACONDE",
    "CAHUACHO",
    "CALLALLI",
    "CAMANA",
    "CARAVELI",
    "CAYARANI",
    "CAYLLOMA",
    "CAYMA",
    "CERRO COLORADO",
    "CHACHAS",
    "CHALA",
    "CHAPARRA",
    "CHARACATO",
    "CHARCANA",
    "CHICHAS",
    "CHIGUATA",
    "CHILCAYMARCA",
    "CHIVAY",
    "CHOCO",
    "CHUQUIBAMBA",
    "COCACHACRA",
    "COPORAQUE",
    "COTAHUASI",
    "DEAN VALDIVIA",
    "HUAMBO",
    "HUANCA",
    "HUANCARQUI",
    "HUANUHUANU",
    "HUAYNACOTAS",
    "ICHUPAMPA",
    "IRAY",
    "ISLAY",
    "JACOBO HUNTER",
    "JAQUI",
    "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE MARIA QUIMPER",
    "LA JOYA",
    "LARI",
    "LLUTA",
    "LOMAS",
    "MACA",
    "MACHAGUAY",
    "MADRIGAL",
    "MAJES",
    "MARIANO MELGAR",
    "MARIANO NICOLAS VALCARCEL",
    "MARISCAL CACERES",
    "MEJIA",
    "MIRAFLORES",
    "MOLLEBAYA",
    "MOLLENDO",
    "NICOLAS DE PIEROLA",
    "OCONA",
    "ORCOPAMPA",
    "PAMPACOLCA",
    "PAMPAMARCA",
    "PAUCARPATA",
    "POCSI",
    "POLOBAYA",
    "PUNTA DE BOMBON",
    "PUYCA",
    "QUECHUALLA",
    "QUEQUENA",
    "QUICACHA",
    "QUILCA",
    "RIO GRANDE",
    "SABANDIA",
    "SACHACA",
    "SALAMANCA",
    "SAMUEL PASTOR",
    "SAN ANTONIO DE CHUCA",
    "SAN JUAN DE SIGUAS",
    "SAN JUAN DE TARUCANI",
    "SANTA ISABEL DE SIGUAS",
    "SANTA RITA DE SIGUAS",
    "SAYLA",
    "SIBAYO",
    "SOCABAYA",
    "TAPAY",
    "TAURIA",
    "TIABAYA",
    "TIPAN",
    "TISCO",
    "TOMEPAMPA",
    "TORO",
    "TUTI",
    "UCHUMAYO",
    "UNON",
    "URACA",
    "VIRACO",
    "VITOR",
    "YANAHUARA",
    "YANAQUIHUA",
    "YANQUE",
    "YARABAMBA",
    "YAUCA",
    "YURA",
  ]),
  "AYACUCHO": new Set([
    "ACCOMARCA",
    "ACOCRO",
    "ACOS VINCHOS",
    "ALCAMENCA",
    "ANCHIHUAY",
    "ANCO",
    "ANDRES AVELINO CACERES DORREGARAY",
    "APONGO",
    "ASQUIPATA",
    "AUCARA",
    "AYACUCHO",
    "AYAHUANCO",
    "AYNA",
    "BELEN",
    "CABANA",
    "CANARIA",
    "CANAYRE",
    "CANGALLO",
    "CARAPO",
    "CARHUANCA",
    "CARMEN ALTO",
    "CARMEN SALCEDO",
    "CAYARA",
    "CHACA",
    "CHALCOS",
    "CHAVINA",
    "CHIARA",
    "CHILCAS",
    "CHILCAYOC",
    "CHIPAO",
    "CHUMPI",
    "CHUNGUI",
    "CHUSCHI",
    "COLCA",
    "COLTA",
    "CONCEPCION",
    "CORACORA",
    "CORCULLA",
    "CORONEL CASTANEDA",
    "HUAC-HUAS",
    "HUACANA",
    "HUAMANGUILLA",
    "HUAMANQUIQUIA",
    "HUAMBALPA",
    "HUANCAPI",
    "HUANCARAYLLA",
    "HUANTA",
    "HUAYA",
    "IGUAIN",
    "INDEPENDENCIA",
    "JESUS NAZARENO",
    "LAMPA",
    "LARAMATE",
    "LEONCIO PRADO",
    "LLAUTA",
    "LLOCHEGUA",
    "LOS MOROCHUCOS",
    "LUCANAS",
    "LUIS CARRANZA",
    "LURICOCHA",
    "MARCABAMBA",
    "MARIA PARADO DE BELLIDO",
    "MORCOLLA",
    "OCANA",
    "OCROS",
    "ORONCCOY",
    "OTOCA",
    "OYOLO",
    "PACAPAUSA",
    "PACAYCASA",
    "PAICO",
    "PARARCA",
    "PARAS",
    "PAUSA",
    "PUCACOLPA",
    "PULLO",
    "PUQUIO",
    "PUYUSCA",
    "QUEROBAMBA",
    "QUINUA",
    "SACSAMARCA",
    "SAISA",
    "SAMUGARI",
    "SAN CRISTOBAL",
    "SAN FRANCISCO DE RAVACAYCO",
    "SAN JAVIER DE ALPABAMBA",
    "SAN JOSE DE TICLLAS",
    "SAN JOSE DE USHUA",
    "SAN JUAN",
    "SAN JUAN BAUTISTA",
    "SAN MIGUEL",
    "SAN PEDRO",
    "SAN PEDRO DE LARCAY",
    "SAN PEDRO DE PALCO",
    "SAN SALVADOR DE QUIJE",
    "SANCOS",
    "SANTA ANA DE HUAYCAHUACHO",
    "SANTA LUCIA",
    "SANTA ROSA",
    "SANTIAGO DE LUCANAMARCA",
    "SANTIAGO DE PAUCARAY",
    "SANTIAGO DE PISCHA",
    "SANTILLANA",
    "SARA SARA",
    "SARHUA",
    "SAURAMA",
    "SIVIA",
    "SOCOS",
    "SORAS",
    "TAMBILLO",
    "TAMBO",
    "TOTOS",
    "UCHURACCAY",
    "UPAHUACHO",
    "VILCANCHOS",
    "VILCAS HUAMAN",
    "VINCHOS",
    "VISCHONGO",
  ]),
  "CAJAMARCA": new Set([
    "ANDABAMBA",
    "ANGUIA",
    "ASUNCION",
    "BAMBAMARCA",
    "BELLAVISTA",
    "BOLIVAR",
    "CACHACHI",
    "CAJABAMBA",
    "CAJAMARCA",
    "CALLAYUC",
    "CALQUIS",
    "CATACHE",
    "CATILLUC",
    "CELENDIN",
    "CHADIN",
    "CHALAMARCA",
    "CHANCAY",
    "CHANCAYBANOS",
    "CHETILLA",
    "CHIGUIRIP",
    "CHILETE",
    "CHIMBAN",
    "CHIRINOS",
    "CHONTALI",
    "CHOROPAMPA",
    "CHOROS",
    "CHOTA",
    "CHUGUR",
    "CHUMUCH",
    "COCHABAMBA",
    "COLASAY",
    "CONCHAN",
    "CONDEBAMBA",
    "CONTUMAZA",
    "CORTEGANA",
    "COSPAN",
    "CUJILLO",
    "CUPISNIQUE",
    "CUTERVO",
    "EDUARDO VILLANUEVA",
    "EL PRADO",
    "ENCANADA",
    "GREGORIO PITA",
    "GUZMANGO",
    "HUABAL",
    "HUALGAYOC",
    "HUAMBOS",
    "HUARANGO",
    "HUASMIN",
    "ICHOCAN",
    "JAEN",
    "JESUS",
    "JORGE CHAVEZ",
    "JOSE GALVEZ",
    "JOSE MANUEL QUIROZ",
    "JOSE SABOGAL",
    "LA COIPA",
    "LA ESPERANZA",
    "LA FLORIDA",
    "LA LIBERTAD DE PALLAN",
    "LA RAMADA",
    "LAJAS",
    "LAS PIRIAS",
    "LLACANORA",
    "LLAMA",
    "LLAPA",
    "LOS BANOS DEL INCA",
    "MAGDALENA",
    "MATARA",
    "MIGUEL IGLESIAS",
    "MIRACOSTA",
    "NAMBALLE",
    "NAMORA",
    "NANCHOC",
    "NIEPOS",
    "NINABAMBA",
    "OXAMARCA",
    "PACCHA",
    "PEDRO GALVEZ",
    "PIMPINGOS",
    "PION",
    "POMAHUACA",
    "PUCARA",
    "PULAN",
    "QUEROCOTILLO",
    "QUEROCOTO",
    "SALLIQUE",
    "SAN ANDRES DE CUTERVO",
    "SAN BENITO",
    "SAN BERNARDINO",
    "SAN FELIPE",
    "SAN GREGORIO",
    "SAN IGNACIO",
    "SAN JOSE DE LOURDES",
    "SAN JOSE DEL ALTO",
    "SAN JUAN",
    "SAN JUAN DE CUTERVO",
    "SAN JUAN DE LICUPIS",
    "SAN LUIS",
    "SAN LUIS DE LUCMA",
    "SAN MIGUEL",
    "SAN PABLO",
    "SAN SILVESTRE DE COCHAN",
    "SANTA CRUZ",
    "SANTA CRUZ DE TOLED",
    "SANTA ROSA",
    "SANTO DOMINGO DE LA CAPILLA",
    "SANTO TOMAS",
    "SAUCEPAMPA",
    "SEXI",
    "SITACOCHA",
    "SOCOTA",
    "SOROCHUCO",
    "SUCRE",
    "TABACONAS",
    "TACABAMBA",
    "TANTARICA",
    "TOCMOCHE",
    "TONGOD",
    "TORIBIO CASANOVA",
    "TUMBADEN",
    "UNION AGUA BLANCA",
    "UTCO",
    "UTICYACU",
    "YAUYUCAN",
    "YONAN",
  ]),
  "CALLAO": new Set([
    "BELLAVISTA",
    "CALLAO",
    "CARMEN DE LA LEGUA REYNOSO",
    "LA PERLA",
    "LA PUNTA",
    "MI PERU",
    "VENTANILLA",
  ]),
  "CUSCO": new Set([
    "ACCHA",
    "ACOMAYO",
    "ACOPIA",
    "ACOS",
    "ALTO PICHIGUA",
    "ANCAHUASI",
    "ANDAHUAYLILLAS",
    "ANTA",
    "CACHIMAYO",
    "CAICAY",
    "CALCA",
    "CAMANTI",
    "CAPACMARCA",
    "CCAPI",
    "CCARHUAYO",
    "CCATCA",
    "CCORCA",
    "CHALLABAMBA",
    "CHAMACA",
    "CHECACUPE",
    "CHECCA",
    "CHINCHAYPUJIO",
    "CHINCHERO",
    "COLCHA",
    "COLQUEMARCA",
    "COLQUEPATA",
    "COMBAPATA",
    "CONDOROMA",
    "COPORAQUE",
    "COYA",
    "CUSCO",
    "CUSIPATA",
    "ECHARATE",
    "ESPINAR",
    "HUANCARANI",
    "HUANOQUITE",
    "HUARO",
    "HUAROCONDO",
    "HUAYLLABAMBA",
    "HUAYOPATA",
    "INKAWASI",
    "KIMBIRI",
    "KOSNIPATA",
    "KUNTURKANKI",
    "LAMAY",
    "LANGUI",
    "LARES",
    "LAYO",
    "LIMATAMBO",
    "LIVITACA",
    "LLUSCO",
    "LUCRE",
    "MACHUPICCHU",
    "MARANGANI",
    "MARANURA",
    "MARAS",
    "MARCAPATA",
    "MEGANTONI",
    "MOLLEPATA",
    "MOSOC LLACTA",
    "OCOBAMBA",
    "OCONGATE",
    "OCORURO",
    "OLLANTAYTAMBO",
    "OMACHA",
    "OROPESA",
    "PACCARITAMBO",
    "PALLPATA",
    "PAMPAMARCA",
    "PARURO",
    "PAUCARTAMBO",
    "PICHARI",
    "PICHIGUA",
    "PILLPINTO",
    "PISAC",
    "PITUMARCA",
    "POMACANCHI",
    "POROY",
    "PUCYURA",
    "QUEHUE",
    "QUELLOUNO",
    "QUINOTA",
    "QUIQUIJANA",
    "RONDOCAN",
    "SAN JERONIMO",
    "SAN PABLO",
    "SAN PEDRO",
    "SAN SALVADOR",
    "SAN SEBASTIAN",
    "SANGARARA",
    "SANTA ANA",
    "SANTA TERESA",
    "SANTIAGO",
    "SANTO TOMAS",
    "SAYLLA",
    "SICUANI",
    "SUYCKUTAMBO",
    "TARAY",
    "TINTA",
    "TUPAC AMARU",
    "URCOS",
    "URUBAMBA",
    "VELILLE",
    "VILCABAMBA",
    "VILLA KINTIARINA",
    "VILLA VIRGEN",
    "WANCHAQ",
    "YANAOCA",
    "YANATILE",
    "YAURISQUE",
    "YUCAY",
    "ZURITE",
  ]),
  "HUANCAVELICA": new Set([
    "ACOBAMBA",
    "ACOBAMBILLA",
    "ACORIA",
    "ACOSTAMBO",
    "ACRAQUIA",
    "AHUAYCHA",
    "ANCHONGA",
    "ANCO",
    "ANDABAMBA",
    "ANDAYMARCA",
    "ANTA",
    "ARMA",
    "ASCENSION",
    "AURAHUA",
    "AYAVI",
    "CAJA",
    "CALLANMARCA",
    "CAPILLAS",
    "CASTROVIRREYNA",
    "CCOCHACCASA",
    "CHINCHIHUASI",
    "CHINCHO",
    "CHUPAMARCA",
    "CHURCAMPA",
    "COCAS",
    "COLCABAMBA",
    "CONAYCA",
    "CONGALLA",
    "CORDOVA",
    "COSME",
    "CUENCA",
    "DANIEL HERNANDEZ",
    "EL CARMEN",
    "HUACHOCOLPA",
    "HUACHOS",
    "HUAMATAMBO",
    "HUANCA-HUANCA",
    "HUANCAVELICA",
    "HUANDO",
    "HUARIBAMBA",
    "HUAYACUNDO ARMA",
    "HUAYLLAHUARA",
    "HUAYLLAY GRANDE",
    "HUAYTARA",
    "IZCUCHACA",
    "JULCAMARCA",
    "LA MERCED",
    "LARAMARCA",
    "LARIA",
    "LIRCAY",
    "LOCROJA",
    "MANTA",
    "MARCAS",
    "MARISCAL CACERES",
    "MOLLEPAMPA",
    "MOYA",
    "NAHUIMPUQUIO",
    "NUEVO OCCORO",
    "OCOYO",
    "PACHAMARCA",
    "PALCA",
    "PAMPAS",
    "PAUCARA",
    "PAUCARBAMBA",
    "PAZOS",
    "PICHOS",
    "PILCHACA",
    "PILPICHACA",
    "POMACOCHA",
    "QUERCO",
    "QUICHUAS",
    "QUISHUAR",
    "QUITO-ARMA",
    "ROBLE",
    "ROSARIO",
    "SALCABAMBA",
    "SALCAHUASI",
    "SAN ANTONIO DE ANTAPARCO",
    "SAN ANTONIO DE CUSICANCHA",
    "SAN FRANCISCO DE SANGAYAICO",
    "SAN ISIDRO",
    "SAN JUAN",
    "SAN MARCOS DE ROCCHAC",
    "SAN MIGUEL DE MAYOCC",
    "SAN PEDRO DE CORIS",
    "SANTA ANA",
    "SANTIAGO DE CHOCORVOS",
    "SANTIAGO DE QUIRAHUARA",
    "SANTIAGO DE TUCUMA",
    "SANTO DOMINGO DE CAPILLAS",
    "SANTO TOMAS DE PATA",
    "SECCLLA",
    "SURCUBAMBA",
    "TAMBO",
    "TANTARA",
    "TICRAPO",
    "TINTAY PUNCU",
    "VILCA",
    "YAULI",
  ]),
  "HUANUCO": new Set([
    "AMARILIS",
    "AMBO",
    "APARICIO POMARES",
    "ARANCAY",
    "BANOS",
    "CAHUAC",
    "CANCHABAMBA",
    "CASTILLO GRANDE",
    "CAYNA",
    "CHACABAMBA",
    "CHAGLLA",
    "CHAVIN DE PARIARCA",
    "CHAVINILLO",
    "CHINCHAO",
    "CHOLON",
    "CHORAS",
    "CHUQUIS",
    "CHURUBAMBA",
    "COCHABAMBA",
    "CODO DEL POZUZO",
    "COLPAS",
    "CONCHAMARCA",
    "DANIEL ALOMIA ROBLES",
    "HERMILIO VALDIZAN",
    "HONORIA",
    "HUACAR",
    "HUACAYBAMBA",
    "HUACRACHUCO",
    "HUANUCO",
    "JACAS CHICO",
    "JACAS GRANDE",
    "JESUS",
    "JIRCAN",
    "JIVIA",
    "JOSE CRESPO Y CASTILLO",
    "LA MORADA",
    "LA UNION",
    "LLATA",
    "LUYANDO",
    "MARGOS",
    "MARIANO DAMASO BERAUN",
    "MARIAS",
    "MIRAFLORES",
    "MOLINO",
    "MONZON",
    "OBAS",
    "PACHAS",
    "PAMPAMARCA",
    "PANAO",
    "PILLCO MARCA",
    "PINRA",
    "PUCAYACU",
    "PUEBLO NUEVO",
    "PUERTO INCA",
    "PUNCHAO",
    "PUNOS",
    "QUEROPALCA",
    "QUISQUI (KICHKI)",
    "QUIVILLA",
    "RIPAN",
    "RONDOS",
    "RUPA-RUPA",
    "SAN BUENAVENTURA",
    "SAN FRANCISCO",
    "SAN FRANCISCO DE ASIS",
    "SAN FRANCISCO DE CAYRAN",
    "SAN MIGUEL DE CAURI",
    "SAN PABLO DE PILLAO",
    "SAN PEDRO DE CHAULAN",
    "SAN RAFAEL",
    "SANTA MARIA DEL VALLE",
    "SANTA ROSA DE ALTO YANAJANCA",
    "SANTO DOMINGO DE ANDA",
    "SHUNQUI",
    "SILLAPATA",
    "SINGA",
    "TANTAMAYO",
    "TOMAY KICHWA",
    "TOURNAVISTA",
    "UMARI",
    "YACUS",
    "YANAS",
    "YARUMAYO",
    "YUYAPICHIS",
  ]),
  "ICA": new Set([
    "ALTO LARAN",
    "CHANGUILLO",
    "CHAVIN",
    "CHINCHA ALTA",
    "CHINCHA BAJA",
    "EL CARMEN",
    "EL INGENIO",
    "GROCIO PRADO",
    "HUANCANO",
    "HUMAY",
    "ICA",
    "INDEPENDENCIA",
    "LA TINGUINA",
    "LLIPATA",
    "LOS AQUIJES",
    "MARCONA",
    "NASCA",
    "OCUCAJE",
    "PACHACUTEC",
    "PALPA",
    "PARACAS",
    "PARCONA",
    "PISCO",
    "PUEBLO NUEVO",
    "RIO GRANDE",
    "SALAS",
    "SAN ANDRES",
    "SAN CLEMENTE",
    "SAN JOSE DE LOS MOLINOS",
    "SAN JUAN BAUTISTA",
    "SAN JUAN DE YANAC",
    "SAN PEDRO DE HUACARPANA",
    "SANTA CRUZ",
    "SANTIAGO",
    "SUBTANJALLA",
    "SUNAMPE",
    "TAMBO DE MORA",
    "TATE",
    "TIBILLO",
    "TUPAC AMARU INCA",
    "VISTA ALEGRE",
    "YAUCA DEL ROSARIO",
  ]),
  "JUNIN": new Set([
    "ACO",
    "ACOBAMBA",
    "ACOLLA",
    "AHUAC",
    "ANDAMARCA",
    "APATA",
    "ATAURA",
    "CANCHAYLLO",
    "CARHUACALLANGA",
    "CARHUAMAYO",
    "CHACAPALPA",
    "CHACAPAMPA",
    "CHAMBARA",
    "CHANCHAMAYO",
    "CHICCHE",
    "CHILCA",
    "CHONGOS ALTO",
    "CHONGOS BAJO",
    "CHUPACA",
    "CHUPURO",
    "COCHAS",
    "COLCA",
    "COMAS",
    "CONCEPCION",
    "COVIRIALI",
    "CULLHUAS",
    "CURICACA",
    "EL MANTARO",
    "EL TAMBO",
    "HEROINAS TOLEDO",
    "HUACHAC",
    "HUACRAPUQUIO",
    "HUALHUAS",
    "HUAMALI",
    "HUAMANCACA CHICO",
    "HUANCAN",
    "HUANCAYO",
    "HUARICOLCA",
    "HUARIPAMPA",
    "HUASAHUASI",
    "HUASICANCHA",
    "HUAY-HUAY",
    "HUAYUCACHI",
    "HUERTAS",
    "INGENIO",
    "JANJAILLO",
    "JAUJA",
    "JULCAN",
    "JUNIN",
    "LA OROYA",
    "LA UNION",
    "LEONOR ORDONEZ",
    "LLAYLLA",
    "LLOCLLAPAMPA",
    "MANZANARES",
    "MARCAPOMACOCHA",
    "MARCO",
    "MARISCAL CASTILLA",
    "MASMA",
    "MASMA CHICCHE",
    "MATAHUASI",
    "MAZAMARI",
    "MITO",
    "MOLINOS",
    "MONOBAMBA",
    "MOROCOCHA",
    "MUQUI",
    "MUQUIYAUYO",
    "NUEVE DE JULIO",
    "ONDORES",
    "ORCOTUNA",
    "PACA",
    "PACCHA",
    "PALCA",
    "PALCAMAYO",
    "PAMPA HERMOSA",
    "PANCAN",
    "PANGOA",
    "PARCO",
    "PARIAHUANCA",
    "PERENE",
    "PICHANAQUI",
    "PILCOMAYO",
    "POMACANCHA",
    "PUCARA",
    "QUICHUAY",
    "QUILCAS",
    "RICRAN",
    "RIO NEGRO",
    "RIO TAMBO",
    "SAN AGUSTIN",
    "SAN JERONIMO DE TUNAN",
    "SAN JOSE DE QUERO",
    "SAN JUAN DE ISCOS",
    "SAN JUAN DE JARPA",
    "SAN LORENZO",
    "SAN LUIS DE SHUARO",
    "SAN PEDRO DE CAJAS",
    "SAN PEDRO DE CHUNAN",
    "SAN RAMON",
    "SANO",
    "SANTA BARBARA DE CARHUACAYAN",
    "SANTA ROSA DE OCOPA",
    "SANTA ROSA DE SACCO",
    "SANTO DOMINGO DE ACOBAMBA",
    "SAPALLANGA",
    "SATIPO",
    "SAUSA",
    "SICAYA",
    "SINCOS",
    "SUITUCANCHA",
    "TAPO",
    "TARMA",
    "TRES DE DICIEMBRE",
    "TUNAN MARCA",
    "ULCUMAYO",
    "VIQUES",
    "VITOC",
    "VIZCATAN DEL ENE",
    "YANACANCHA",
    "YAULI",
    "YAUYOS",
  ]),
  "LA LIBERTAD": new Set([
    "AGALLPAMPA",
    "ANGASMARCA",
    "ASCOPE",
    "BAMBAMARCA",
    "BOLIVAR",
    "BULDIBUYO",
    "CACHICADAN",
    "CALAMARCA",
    "CARABAMBA",
    "CASA GRANDE",
    "CASCAS",
    "CHAO",
    "CHARAT",
    "CHEPEN",
    "CHICAMA",
    "CHILLIA",
    "CHOCOPE",
    "CHUGAY",
    "COCHORCO",
    "CONDORMARCA",
    "CURGOS",
    "EL PORVENIR",
    "FLORENCIA DE MORA",
    "GUADALUPE",
    "GUADALUPITO",
    "HUAMACHUCO",
    "HUANCASPATA",
    "HUANCHACO",
    "HUARANCHAL",
    "HUASO",
    "HUAYLILLAS",
    "HUAYO",
    "JEQUETEPEQUE",
    "JULCAN",
    "LA CUESTA",
    "LA ESPERANZA",
    "LAREDO",
    "LONGOTEA",
    "LUCMA",
    "MACHE",
    "MAGDALENA DE CAO",
    "MARCABAL",
    "MARMOT",
    "MOCHE",
    "MOLLEBAMBA",
    "MOLLEPATA",
    "ONGON",
    "OTUZCO",
    "PACANGA",
    "PACASMAYO",
    "PAIJAN",
    "PARANDAY",
    "PARCOY",
    "PATAZ",
    "PIAS",
    "POROTO",
    "PUEBLO NUEVO",
    "QUIRUVILCA",
    "RAZURI",
    "SALAVERRY",
    "SALPO",
    "SAN JOSE",
    "SAN PEDRO DE LLOC",
    "SANAGORAN",
    "SANTA CRUZ DE CHUCA",
    "SANTIAGO DE CAO",
    "SANTIAGO DE CHALLAS",
    "SANTIAGO DE CHUCO",
    "SARIN",
    "SARTIMBAMBA",
    "SAYAPULLO",
    "SIMBAL",
    "SINSICAP",
    "SITABAMBA",
    "TAURIJA",
    "TAYABAMBA",
    "TRUJILLO",
    "UCHUMARCA",
    "UCUNCHA",
    "URPAY",
    "USQUIL",
    "VICTOR LARCO HERRERA",
    "VIRU",
  ]),
  "LAMBAYEQUE": new Set([
    "CANARIS",
    "CAYALTI",
    "CHICLAYO",
    "CHOCHOPE",
    "CHONGOYAPE",
    "ETEN",
    "ETEN PUERTO",
    "FERRENAFE",
    "ILLIMO",
    "INCAHUASI",
    "JAYANCA",
    "JOSE LEONARDO ORTIZ",
    "LA VICTORIA",
    "LAGUNAS",
    "LAMBAYEQUE",
    "MANUEL ANTONIO MESONES MURO",
    "MOCHUMI",
    "MONSEFU",
    "MORROPE",
    "MOTUPE",
    "NUEVA ARICA",
    "OLMOS",
    "OYOTUN",
    "PACORA",
    "PATAPO",
    "PICSI",
    "PIMENTEL",
    "PITIPO",
    "POMALCA",
    "PUCALA",
    "PUEBLO NUEVO",
    "REQUE",
    "SALAS",
    "SAN JOSE",
    "SANA",
    "SANTA ROSA",
    "TUCUME",
    "TUMAN",
  ]),
  "LIMA": new Set([
    "ALIS",
    "ALLAUCA",
    "AMBAR",
    "ANCON",
    "ANDAJES",
    "ANTIOQUIA",
    "ARAHUAY",
    "ASIA",
    "ATAVILLOS ALTO",
    "ATAVILLOS BAJO",
    "ATE",
    "AUCALLAMA",
    "AYAVIRI",
    "AZANGARO",
    "BARRANCA",
    "BARRANCO",
    "BRENA",
    "CACRA",
    "CAJATAMBO",
    "CALANGO",
    "CALETA DE CARQUIN",
    "CALLAHUANCA",
    "CANTA",
    "CARABAYLLO",
    "CARAMPOMA",
    "CARANIA",
    "CATAHUASI",
    "CAUJUL",
    "CERRO AZUL",
    "CHACLACAYO",
    "CHANCAY",
    "CHECRAS",
    "CHICLA",
    "CHILCA",
    "CHOCOS",
    "CHORRILLOS",
    "CIENEGUILLA",
    "COAYLLO",
    "COCHAMARCA",
    "COCHAS",
    "COLONIA",
    "COMAS",
    "COPA",
    "CUENCA",
    "EL AGUSTINO",
    "GORGOR",
    "HONGOS",
    "HUACHO",
    "HUACHUPAMPA",
    "HUALMAY",
    "HUAMANTANGA",
    "HUAMPARA",
    "HUANCAPON",
    "HUANCAYA",
    "HUANEC",
    "HUANGASCAR",
    "HUANTAN",
    "HUANZA",
    "HUARAL",
    "HUAROCHIRI",
    "HUAROS",
    "HUAURA",
    "IHUARI",
    "IMPERIAL",
    "INDEPENDENCIA",
    "JESUS MARIA",
    "LA MOLINA",
    "LA VICTORIA",
    "LACHAQUI",
    "LAHUAYTAMBO",
    "LAMPIAN",
    "LANGA",
    "LARAOS",
    "LEONCIO PRADO",
    "LIMA",
    "LINCE",
    "LINCHA",
    "LOS OLIVOS",
    "LUNAHUANA",
    "LURIGANCHO",
    "LURIN",
    "MADEAN",
    "MAGDALENA DEL MAR",
    "MALA",
    "MANAS",
    "MARIATANA",
    "MATUCANA",
    "MIRAFLORES",
    "NAVAN",
    "NUEVO IMPERIAL",
    "OMAS",
    "OYON",
    "PACARAN",
    "PACARAOS",
    "PACCHO",
    "PACHACAMAC",
    "PACHANGARA",
    "PARAMONGA",
    "PATIVILCA",
    "PUCUSANA",
    "PUEBLO LIBRE",
    "PUENTE PIEDRA",
    "PUNTA HERMOSA",
    "PUNTA NEGRA",
    "PUTINZA",
    "QUILMANA",
    "QUINCHES",
    "QUINOCAY",
    "RICARDO PALMA",
    "RIMAC",
    "SAN ANDRES DE TUPICOCHA",
    "SAN ANTONIO",
    "SAN BARTOLO",
    "SAN BARTOLOME",
    "SAN BORJA",
    "SAN BUENAVENTURA",
    "SAN DAMIAN",
    "SAN ISIDRO",
    "SAN JOAQUIN",
    "SAN JUAN DE IRIS",
    "SAN JUAN DE LURIGANCHO",
    "SAN JUAN DE MIRAFLORES",
    "SAN JUAN DE TANTARANCHE",
    "SAN LORENZO DE QUINTI",
    "SAN LUIS",
    "SAN MARTIN DE PORRES",
    "SAN MATEO",
    "SAN MATEO DE OTAO",
    "SAN MIGUEL",
    "SAN MIGUEL DE ACOS",
    "SAN PEDRO DE CASTA",
    "SAN PEDRO DE HUANCAYRE",
    "SAN PEDRO DE PILAS",
    "SAN VICENTE DE CANETE",
    "SANGALLAYA",
    "SANTA ANITA",
    "SANTA CRUZ DE ANDAMARCA",
    "SANTA CRUZ DE COCACHACRA",
    "SANTA CRUZ DE FLORES",
    "SANTA EULALIA",
    "SANTA LEONOR",
    "SANTA MARIA",
    "SANTA MARIA DEL MAR",
    "SANTA ROSA",
    "SANTA ROSA DE QUIVES",
    "SANTIAGO DE ANCHUCAYA",
    "SANTIAGO DE SURCO",
    "SANTIAGO DE TUNA",
    "SANTO DOMINGO DE LOS OLLEROS",
    "SAYAN",
    "SUMBILCA",
    "SUPE",
    "SUPE PUERTO",
    "SURCO",
    "SURQUILLO",
    "TANTA",
    "TAURIPAMPA",
    "TOMAS",
    "TUPE",
    "VEGUETA",
    "VEINTISIETE DE NOVIEMBRE",
    "VILLA EL SALVADOR",
    "VILLA MARIA DEL TRIUNFO",
    "VINAC",
    "VITIS",
    "YAUYOS",
    "ZUNIGA",
  ]),
  "LORETO": new Set([
    "ALTO NANAY",
    "ALTO TAPICHE",
    "ANDOAS",
    "BALSAPUERTO",
    "BARRANCA",
    "BELEN",
    "CAHUAPANAS",
    "CAPELO",
    "CONTAMANA",
    "EMILIO SAN MARTIN",
    "FERNANDO LORES",
    "INAHUAYA",
    "INDIANA",
    "IQUITOS",
    "JEBEROS",
    "JENARO HERRERA",
    "LAGUNAS",
    "LAS AMAZONAS",
    "MANSERICHE",
    "MAQUIA",
    "MAZAN",
    "MORONA",
    "NAPO",
    "NAUTA",
    "PADRE MARQUEZ",
    "PAMPA HERMOSA",
    "PARINARI",
    "PASTAZA",
    "PEBAS",
    "PUINAHUA",
    "PUNCHANA",
    "PUTUMAYO",
    "RAMON CASTILLA",
    "REQUENA",
    "ROSA PANDURO",
    "SAN JUAN BAUTISTA",
    "SAN PABLO",
    "SANTA CRUZ",
    "SAQUENA",
    "SARAYACU",
    "SOPLIN",
    "TAPICHE",
    "TENIENTE CESAR LOPEZ ROJAS",
    "TENIENTE MANUEL CLAVERO",
    "TIGRE",
    "TORRES CAUSANA",
    "TROMPETEROS",
    "URARINAS",
    "VARGAS GUERRA",
    "YAGUAS",
    "YAQUERANA",
    "YAVARI",
    "YURIMAGUAS",
  ]),
  "MADRE DE DIOS": new Set([
    "FITZCARRALD",
    "HUEPETUHE",
    "IBERIA",
    "INAMBARI",
    "INAPARI",
    "LABERINTO",
    "LAS PIEDRAS",
    "MADRE DE DIOS",
    "MANU",
    "TAHUAMANU",
    "TAMBOPATA",
  ]),
  "MOQUEGUA": new Set([
    "CARUMAS",
    "CHOJATA",
    "COALAQUE",
    "CUCHUMBAYA",
    "EL ALGARROBAL",
    "ICHUNA",
    "ILO",
    "LA CAPILLA",
    "LLOQUE",
    "MATALAQUE",
    "MOQUEGUA",
    "OMATE",
    "PACOCHA",
    "PUQUINA",
    "QUINISTAQUILLAS",
    "SAMEGUA",
    "SAN CRISTOBAL",
    "TORATA",
    "UBINAS",
    "YUNGA",
  ]),
  "PASCO": new Set([
    "CHACAYAN",
    "CHAUPIMARCA",
    "CHONTABAMBA",
    "CONSTITUCION",
    "GOYLLARISQUIZGA",
    "HUACHON",
    "HUANCABAMBA",
    "HUARIACA",
    "HUAYLLAY",
    "NINACACA",
    "OXAPAMPA",
    "PALCAZU",
    "PALLANCHACRA",
    "PAUCAR",
    "PAUCARTAMBO",
    "POZUZO",
    "PUERTO BERMUDEZ",
    "SAN FRANCISCO DE ASIS DE YARUSYACAN",
    "SAN PEDRO DE PILLAO",
    "SANTA ANA DE TUSI",
    "SIMON BOLIVAR",
    "TAPUC",
    "TICLACAYAN",
    "TINYAHUARCO",
    "VICCO",
    "VILCABAMBA",
    "VILLA RICA",
    "YANACANCHA",
    "YANAHUANCA",
  ]),
  "PIURA": new Set([
    "AMOTAPE",
    "ARENAL",
    "AYABACA",
    "BELLAVISTA",
    "BELLAVISTA DE LA UNION",
    "BERNAL",
    "BUENOS AIRES",
    "CANCHAQUE",
    "CASTILLA",
    "CATACAOS",
    "CHALACO",
    "CHULUCANAS",
    "COLAN",
    "CRISTO NOS VALGA",
    "CURA MORI",
    "EL ALTO",
    "EL CARMEN DE LA FRONTERA",
    "EL TALLAN",
    "FRIAS",
    "HUANCABAMBA",
    "HUARMACA",
    "IGNACIO ESCUDERO",
    "JILILI",
    "LA ARENA",
    "LA BREA",
    "LA HUACA",
    "LA MATANZA",
    "LA UNION",
    "LAGUNAS",
    "LALAQUIZ",
    "LANCONES",
    "LAS LOMAS",
    "LOBITOS",
    "LOS ORGANOS",
    "MANCORA",
    "MARCAVELICA",
    "MIGUEL CHECA",
    "MONTERO",
    "MORROPON",
    "PACAIPAMPA",
    "PAIMAS",
    "PAITA",
    "PARINAS",
    "PIURA",
    "QUERECOTILLO",
    "RINCONADA LLICUAR",
    "SALITRAL",
    "SAN JUAN DE BIGOTE",
    "SAN MIGUEL DE EL FAIQUE",
    "SANTA CATALINA DE MOSSA",
    "SANTO DOMINGO",
    "SAPILLICA",
    "SECHURA",
    "SICCHEZ",
    "SONDOR",
    "SONDORILLO",
    "SULLANA",
    "SUYO",
    "TAMARINDO",
    "TAMBO GRANDE",
    "VEINTISEIS DE OCTUBRE",
    "VICE",
    "VICHAYAL",
    "YAMANGO",
  ]),
  "PUNO": new Set([
    "ACHAYA",
    "ACORA",
    "AJOYANI",
    "ALTO INAMBARI",
    "AMANTANI",
    "ANANEA",
    "ANAPIA",
    "ANTAUTA",
    "ARAPA",
    "ASILLO",
    "ATUNCOLLA",
    "AYAPATA",
    "AYAVIRI",
    "AZANGARO",
    "CABANA",
    "CABANILLA",
    "CABANILLAS",
    "CALAPUJA",
    "CAMINACA",
    "CAPACHICA",
    "CAPAZO",
    "CARACOTO",
    "CHUCUITO",
    "CHUPA",
    "COASA",
    "COATA",
    "COJATA",
    "CONDURIRI",
    "CONIMA",
    "COPANI",
    "CORANI",
    "CRUCERO",
    "CUPI",
    "CUTURAPI",
    "CUYOCUYO",
    "DESAGUADERO",
    "HUACULLANI",
    "HUANCANE",
    "HUATA",
    "HUATASANI",
    "HUAYRAPATA",
    "ILAVE",
    "INCHUPALLA",
    "ITUATA",
    "JOSE DOMINGO CHOQUEHUANCA",
    "JULI",
    "JULIACA",
    "KELLUYO",
    "LAMPA",
    "LIMBANI",
    "LLALLI",
    "MACARI",
    "MACUSANI",
    "MANAZO",
    "MOHO",
    "MUNANI",
    "NICASIO",
    "NUNOA",
    "OCUVIRI",
    "OLLACHEA",
    "OLLARAYA",
    "ORURILLO",
    "PALCA",
    "PARATIA",
    "PATAMBUCO",
    "PAUCARCOLLA",
    "PEDRO VILCA APAZA",
    "PHARA",
    "PICHACANI",
    "PILCUYO",
    "PISACOMA",
    "PLATERIA",
    "POMATA",
    "POTONI",
    "PUCARA",
    "PUNO",
    "PUSI",
    "PUTINA",
    "QUIACA",
    "QUILCAPUNCU",
    "ROSASPATA",
    "SAMAN",
    "SAN ANTON",
    "SAN ANTONIO",
    "SAN GABAN",
    "SAN JOSE",
    "SAN JUAN DE SALINAS",
    "SAN JUAN DEL ORO",
    "SAN MIGUEL",
    "SAN PEDRO DE PUTINA PUNCO",
    "SANDIA",
    "SANTA LUCIA",
    "SANTA ROSA",
    "SANTIAGO DE PUPUJA",
    "SINA",
    "TARACO",
    "TILALI",
    "TINICACHI",
    "TIQUILLACA",
    "TIRAPATA",
    "UMACHIRI",
    "UNICACHI",
    "USICAYOS",
    "VILAVILA",
    "VILQUE",
    "VILQUE CHICO",
    "YANAHUAYA",
    "YUNGUYO",
    "ZEPITA",
  ]),
  "SAN MARTIN": new Set([
    "AGUA BLANCA",
    "ALBERTO LEVEAU",
    "ALONSO DE ALVARADO",
    "ALTO BIAVO",
    "ALTO SAPOSOA",
    "AWAJUN",
    "BAJO BIAVO",
    "BARRANQUITA",
    "BELLAVISTA",
    "BUENOS AIRES",
    "CACATACHI",
    "CALZADA",
    "CAMPANILLA",
    "CASPISAPA",
    "CAYNARACHI",
    "CHAZUTA",
    "CHIPURANA",
    "CUNUMBUQUI",
    "EL ESLABON",
    "EL PORVENIR",
    "ELIAS SOPLIN VARGAS",
    "HABANA",
    "HUALLAGA",
    "HUICUNGO",
    "HUIMBAYOC",
    "JEPELACIO",
    "JUAN GUERRA",
    "JUANJUI",
    "LA BANDA DE SHILCAYO",
    "LAMAS",
    "MORALES",
    "MOYOBAMBA",
    "NUEVA CAJAMARCA",
    "NUEVO PROGRESO",
    "PACHIZA",
    "PAJARILLO",
    "PAPAPLAYA",
    "PARDO MIGUEL",
    "PICOTA",
    "PILLUANA",
    "PINTO RECODO",
    "PISCOYACU",
    "POLVORA",
    "POSIC",
    "PUCACACA",
    "RIOJA",
    "RUMISAPA",
    "SACANCHE",
    "SAN ANTONIO",
    "SAN CRISTOBAL",
    "SAN FERNANDO",
    "SAN HILARION",
    "SAN JOSE DE SISA",
    "SAN MARTIN",
    "SAN PABLO",
    "SAN RAFAEL",
    "SAN ROQUE DE CUMBAZA",
    "SANTA ROSA",
    "SAPOSOA",
    "SAUCE",
    "SHAMBOYACU",
    "SHANAO",
    "SHAPAJA",
    "SHATOJA",
    "SHUNTE",
    "SORITOR",
    "TABALOSOS",
    "TARAPOTO",
    "TINGO DE PONASA",
    "TINGO DE SAPOSOA",
    "TOCACHE",
    "TRES UNIDOS",
    "UCHIZA",
    "YANTALO",
    "YORONGOS",
    "YURACYACU",
    "ZAPATERO",
  ]),
  "TACNA": new Set([
    "ALTO DE LA ALIANZA",
    "CAIRANI",
    "CALANA",
    "CAMILACA",
    "CANDARAVE",
    "CIUDAD NUEVA",
    "CORONEL GREGORIO ALBARRACIN LANCHIPA",
    "CURIBAYA",
    "ESTIQUE",
    "ESTIQUE-PAMPA",
    "HEROES ALBARRACIN",
    "HUANUARA",
    "ILABAYA",
    "INCLAN",
    "ITE",
    "LA YARADA LOS PALOS",
    "LOCUMBA",
    "PACHIA",
    "PALCA",
    "POCOLLAY",
    "QUILAHUANI",
    "SAMA",
    "SITAJARA",
    "SUSAPAYA",
    "TACNA",
    "TARATA",
    "TARUCACHI",
    "TICACO",
  ]),
  "TUMBES": new Set([
    "AGUAS VERDES",
    "CANOAS DE PUNTA SAL",
    "CASITAS",
    "CORRALES",
    "LA CRUZ",
    "MATAPALO",
    "PAMPAS DE HOSPITAL",
    "PAPAYAL",
    "SAN JACINTO",
    "SAN JUAN DE LA VIRGEN",
    "TUMBES",
    "ZARUMILLA",
    "ZORRITOS",
  ]),
  "UCAYALI": new Set([
    "ALEXANDER VON HUMBOLDT",
    "CALLERIA",
    "CAMPOVERDE",
    "CURIMANA",
    "IPARIA",
    "IRAZOLA",
    "MANANTAY",
    "MASISEA",
    "NESHUYA",
    "NUEVA REQUENA",
    "PADRE ABAD",
    "PURUS",
    "RAYMONDI",
    "SEPAHUA",
    "TAHUANIA",
    "YARINACOCHA",
    "YURUA",
  ]),
};

/**
 * true si `distrito` no pertenece al universo conocido del `departamento`
 * declarado. `false` (no sospechoso) cuando falta el distrito o cuando no
 * tenemos catálogo para ese departamento — nunca bloquea la ingesta, solo
 * marca la fila para revisión.
 */
export function distritoEsSospechoso(departamento: string, distrito: string | null): boolean {
  if (!distrito) return false;
  const catalogo = DISTRITOS_POR_DEPARTAMENTO[departamento.toUpperCase().trim()];
  if (!catalogo) return false;
  return !catalogo.has(distrito.toUpperCase().trim());
}
