name: emergencias-indeci

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: emergencias_indeci
      POSTGRES_PASSWORD: emergencias_indeci
      POSTGRES_DB: emergencias_indeci
    ports:
      - "127.0.0.1:5466:5432"
    volumes:
      - emergencias_indeci_pgdata:/var/lib/postgresql/data

volumes:
  emergencias_indeci_pgdata:

networks:
  default:
    name: appsperu_shared
    external: true
