name: ceplan-estrategico

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ceplan
      POSTGRES_PASSWORD: ceplan
      POSTGRES_DB: ceplan_estrategico
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - ceplan_pgdata:/var/lib/postgresql/data

volumes:
  ceplan_pgdata:
    name: api_ceplan_pgdata
    external: false
